"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import {
  ArrowPath,
  Bolt,
  Clock,
  ExclamationCircle,
  Pause,
  PlaySolid,
  Plus,
  Robot,
  Sparkles,
  Trash,
} from "@medusajs/icons"
import { cn } from "@lib/util/cn"
import { useMerchantAuth } from "@lib/merchant-admin/auth"
import {
  ApiError,
  deleteMarketingAgent,
  deleteMarketingSchedule,
  generateAgentPosts,
  listMarketingAgents,
  listSocialAccounts,
  updateMarketingAgent,
  type MarketingAgent,
} from "@lib/merchant-admin/api"
import { PageHeader } from "@components/merchant-admin/page-header"
import { EmptyState } from "@components/merchant-admin/empty-state"
import { KpiCard } from "@components/merchant-admin/kpi-card"
import { Modal } from "@components/merchant-admin/modal"
import { PlatformIcons, platformMeta } from "../posts/post-utils"
import { AgentWizard, type WizardStep } from "./agent-wizard"
import { cadenceSummary, modeLabel, postTypeLabel, timeAgo } from "./agent-utils"

/**
 * AI agents — the list.
 *
 * An agent is a standing configuration (platforms, brand voice, post types,
 * voice, cadence, mode) that writes and places posts on its own. Everything a
 * merchant can do to one lives here: open the studio, generate on demand,
 * pause, delete.
 */
export default function MarketingAgentsPage() {
  const { token } = useMerchantAuth()

  const [agents, setAgents] = useState<MarketingAgent[]>([])
  const [connectedCount, setConnectedCount] = useState<number | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [flash, setFlash] = useState<string | null>(null)

  const [wizard, setWizard] = useState<{ id: string | null; step: WizardStep } | null>(
    null
  )
  const [busyId, setBusyId] = useState<string | null>(null)
  const [batchFor, setBatchFor] = useState<MarketingAgent | null>(null)
  const [batchCount, setBatchCount] = useState(3)
  const [confirmDelete, setConfirmDelete] = useState<MarketingAgent | null>(null)
  const [deleting, setDeleting] = useState(false)

  const load = useCallback(() => {
    if (!token) return
    setLoading(true)
    Promise.all([
      listMarketingAgents(token, { limit: 100 }),
      listSocialAccounts(token),
    ])
      .then(([agentsRes, accountsRes]) => {
        setAgents(agentsRes.agents ?? [])
        setConnectedCount(
          (accountsRes.accounts ?? []).filter((a) => a.status === "connected")
            .length
        )
        setError(null)
      })
      .catch((e) =>
        setError(e instanceof ApiError ? e.message : "Could not load your agents.")
      )
      .finally(() => setLoading(false))
  }, [token])

  useEffect(load, [load])

  const stats = useMemo(
    () => ({
      total: agents.length,
      active: agents.filter((a) => a.active).length,
      generated: agents.reduce(
        (sum, a) => sum + (a.playbook?._runtime?.generated_count ?? 0),
        0
      ),
    }),
    [agents]
  )

  const upsert = (agent: MarketingAgent) =>
    setAgents((prev) => {
      const exists = prev.some((a) => a.id === agent.id)
      return exists
        ? prev.map((a) => (a.id === agent.id ? agent : a))
        : [agent, ...prev]
    })

  const toggleActive = async (agent: MarketingAgent) => {
    if (!token) return
    setBusyId(agent.id)
    setError(null)
    try {
      const res = await updateMarketingAgent(token, agent.id, {
        active: !agent.active,
      })
      upsert(res.agent)
      setFlash(
        res.agent.active
          ? `${res.agent.name} is running its cadence.`
          : `${res.agent.name} is paused.`
      )
    } catch (e) {
      setError(
        e instanceof ApiError ? e.message : "Could not update the agent."
      )
    } finally {
      setBusyId(null)
    }
  }

  const generate = async (agent: MarketingAgent, count: number) => {
    if (!token) return
    setBusyId(agent.id)
    setError(null)
    setFlash(null)
    try {
      const res = await generateAgentPosts(token, agent.id, { count })
      const where =
        agent.playbook?.mode === "auto"
          ? "scheduled to publish"
          : "waiting for approval"
      setFlash(
        `${res.count} ${res.count === 1 ? "post" : "posts"} generated by ${agent.name} and ${where}. Open Posts to read them.`
      )
      setBatchFor(null)
      // The run stamps _runtime on the agent; refresh so the card tells the truth.
      load()
    } catch (e) {
      setError(
        e instanceof ApiError
          ? e.message
          : "Could not generate posts for this agent."
      )
    } finally {
      setBusyId(null)
    }
  }

  const remove = async () => {
    if (!token || !confirmDelete) return
    setDeleting(true)
    setError(null)
    try {
      const scheduleId = confirmDelete.playbook?.schedule_id
      await deleteMarketingAgent(token, confirmDelete.id)
      if (scheduleId) {
        // The wizard created this schedule for this agent alone.
        await deleteMarketingSchedule(token, scheduleId).catch(() => undefined)
      }
      setAgents((prev) => prev.filter((a) => a.id !== confirmDelete.id))
      setConfirmDelete(null)
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Could not delete the agent.")
    } finally {
      setDeleting(false)
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI agents"
        description="An agent writes and schedules your social posts on its own: give it your platforms, your brand voice and a cadence, and it keeps the feed running."
        action={
          <button
            type="button"
            onClick={() => setWizard({ id: null, step: 1 })}
            disabled={!token}
            className="inline-flex shrink-0 items-center gap-2 rounded-base bg-grey-90 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-grey-80 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Plus className="h-4 w-4" />
            New agent
          </button>
        }
      />

      {error && (
        <div className="flex items-start gap-2 rounded-base border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">
          <ExclamationCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {flash && (
        <div className="flex items-start justify-between gap-3 rounded-base border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">
          <span>{flash}</span>
          <Link
            href="/dashboard/marketing/posts"
            className="shrink-0 font-medium underline underline-offset-2"
          >
            Open Posts
          </Link>
        </div>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <KpiCard label="Agents" value={stats.total} icon={Robot} />
        <KpiCard label="Active" value={stats.active} icon={PlaySolid} tone="green" />
        <KpiCard label="Posts generated" value={stats.generated} icon={Sparkles} />
      </div>

      {loading ? (
        <div className="rounded-large border border-grey-20 bg-white p-8 text-center text-sm text-grey-50 shadow-borders-base">
          Loading agents...
        </div>
      ) : agents.length === 0 ? (
        <div className="rounded-large border border-grey-20 bg-white p-6 shadow-borders-base">
          <EmptyState
            icon={Robot}
            title="No agents yet"
            description={
              connectedCount === 0
                ? "An agent writes your posts for you: it follows your brand voice, works to a weekly cadence, and either queues each post for your approval or publishes it. Connect a social account first, then create your agent."
                : "An agent writes your posts for you: it follows your brand voice, works to a weekly cadence, and either queues each post for your approval or publishes it. Six short steps and it is running."
            }
            action={
              connectedCount === 0 ? (
                <Link
                  href="/dashboard/marketing/connect"
                  className="inline-flex items-center gap-2 rounded-base bg-grey-90 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-grey-80"
                >
                  Connect a social account
                </Link>
              ) : (
                <button
                  type="button"
                  onClick={() => setWizard({ id: null, step: 1 })}
                  className="inline-flex items-center gap-2 rounded-base bg-grey-90 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-grey-80"
                >
                  <Plus className="h-4 w-4" />
                  Create your first agent
                </button>
              )
            }
          />
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          {agents.map((agent) => {
            const runtime = agent.playbook?._runtime
            const busy = busyId === agent.id
            return (
              <div
                key={agent.id}
                className="flex flex-col rounded-large border border-grey-20 bg-white p-5 shadow-borders-base"
              >
                <div className="flex items-start gap-3">
                  <span className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-grey-10 text-grey-70">
                    <Robot className="h-5 w-5" />
                  </span>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setWizard({ id: agent.id, step: 1 })}
                        className="truncate text-sm font-semibold text-grey-90 hover:underline"
                      >
                        {agent.name}
                      </button>
                      <span
                        className={cn(
                          "inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium",
                          agent.active
                            ? "bg-emerald-50 text-emerald-800"
                            : "bg-amber-50 text-amber-800"
                        )}
                      >
                        {agent.active ? "Active" : "Paused"}
                      </span>
                      <span className="inline-flex items-center rounded-full bg-grey-10 px-2 py-0.5 text-xs font-medium capitalize text-grey-70">
                        {agent.kind}
                      </span>
                      <span
                        className={cn(
                          "inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium",
                          agent.playbook?.mode === "auto"
                            ? "bg-sky-50 text-sky-800"
                            : "bg-grey-10 text-grey-70"
                        )}
                      >
                        {modeLabel(agent.playbook)}
                      </span>
                    </div>

                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      <PlatformIcons platforms={agent.playbook?.platforms ?? []} />
                      <span className="text-xs text-grey-50">
                        {(agent.playbook?.platforms ?? [])
                          .map((p) => platformMeta(p).label)
                          .join(", ") || "No platform"}
                      </span>
                    </div>

                    <p className="mt-2 flex items-center gap-1.5 text-xs text-grey-60">
                      <Clock className="h-3.5 w-3.5 shrink-0 text-grey-40" />
                      {cadenceSummary(agent.playbook)}
                    </p>

                    {!!agent.playbook?.post_types?.length && (
                      <p className="mt-1 text-xs text-grey-50">
                        {agent.playbook.post_types.map(postTypeLabel).join(", ")}
                      </p>
                    )}

                    <p className="mt-2 text-xs text-grey-50">
                      {runtime?.last_run_at
                        ? `Last run ${timeAgo(runtime.last_run_at)}`
                        : "Not run yet"}
                      {runtime?.generated_count
                        ? ` — ${runtime.generated_count} ${runtime.generated_count === 1 ? "post" : "posts"} generated`
                        : ""}
                    </p>

                    {runtime?.last_error && (
                      <p className="mt-2 flex items-start gap-1.5 rounded-base bg-rose-50 p-2 text-xs text-rose-700">
                        <ExclamationCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                        <span>Last run failed: {runtime.last_error}</span>
                      </p>
                    )}
                  </div>
                </div>

                <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-grey-20 pt-4">
                  <button
                    type="button"
                    onClick={() => generate(agent, 1)}
                    disabled={busy || !token}
                    className="inline-flex items-center gap-1.5 rounded-base bg-grey-90 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-grey-80 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {busy ? (
                      <ArrowPath className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <Bolt className="h-3.5 w-3.5" />
                    )}
                    Generate now
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setBatchFor(agent)
                      setBatchCount(3)
                    }}
                    disabled={busy || !token}
                    className="inline-flex items-center gap-1.5 rounded-base border border-grey-30 px-3 py-1.5 text-xs font-medium text-grey-90 transition-colors hover:bg-grey-10 disabled:opacity-50"
                  >
                    <Sparkles className="h-3.5 w-3.5" />
                    Generate batch
                  </button>
                  <button
                    type="button"
                    onClick={() => setWizard({ id: agent.id, step: 1 })}
                    className="inline-flex items-center gap-1.5 rounded-base border border-grey-30 px-3 py-1.5 text-xs font-medium text-grey-90 transition-colors hover:bg-grey-10"
                  >
                    Edit
                  </button>
                  <button
                    type="button"
                    onClick={() => toggleActive(agent)}
                    disabled={busy || !token}
                    className="inline-flex items-center gap-1.5 rounded-base border border-grey-30 px-3 py-1.5 text-xs font-medium text-grey-90 transition-colors hover:bg-grey-10 disabled:opacity-50"
                  >
                    {agent.active ? (
                      <>
                        <Pause className="h-3.5 w-3.5" />
                        Pause
                      </>
                    ) : (
                      <>
                        <PlaySolid className="h-3.5 w-3.5" />
                        Activate
                      </>
                    )}
                  </button>
                  <button
                    type="button"
                    onClick={() => setConfirmDelete(agent)}
                    className="ml-auto inline-flex items-center gap-1.5 rounded-base px-2 py-1.5 text-xs font-medium text-grey-50 transition-colors hover:bg-rose-50 hover:text-rose-700"
                  >
                    <Trash className="h-3.5 w-3.5" />
                    Delete
                  </button>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* Generate batch */}
      <Modal
        open={!!batchFor}
        onClose={() => setBatchFor(null)}
        title="Generate a batch"
        description={
          batchFor?.playbook?.mode === "auto"
            ? "The posts are scheduled and published automatically, exactly as they would be on a cadence slot."
            : "The posts land in the Posts queue as Needs approval. Nothing is published until you approve them."
        }
        size="sm"
      >
        <div className="space-y-5">
          <div>
            <label
              htmlFor="batch-count"
              className="block text-sm font-medium text-grey-70"
            >
              How many posts
            </label>
            <div className="mt-2 flex flex-wrap gap-2">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => setBatchCount(n)}
                  className={cn(
                    "h-9 w-9 rounded-base border text-sm font-medium transition-colors",
                    batchCount === n
                      ? "border-grey-90 bg-grey-90 text-white"
                      : "border-grey-30 text-grey-60 hover:border-grey-90 hover:text-grey-90"
                  )}
                >
                  {n}
                </button>
              ))}
            </div>
            <p className="mt-2 text-xs text-grey-50">
              Each post costs AI credits.
            </p>
          </div>

          <div className="flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={() => setBatchFor(null)}
              className="rounded-base border border-grey-30 px-4 py-2 text-sm font-medium text-grey-90 transition-colors hover:bg-grey-10"
            >
              Cancel
            </button>
            <button
              type="button"
              disabled={!batchFor || busyId === batchFor?.id}
              onClick={() => batchFor && generate(batchFor, batchCount)}
              className="inline-flex items-center gap-2 rounded-base bg-grey-90 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-grey-80 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {batchFor && busyId === batchFor.id ? (
                <ArrowPath className="h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
              Generate {batchCount}
            </button>
          </div>
        </div>
      </Modal>

      {/* Delete */}
      <Modal
        open={!!confirmDelete}
        onClose={() => setConfirmDelete(null)}
        title="Delete this agent"
        description={`${confirmDelete?.name ?? "This agent"} stops running immediately. The posts it already wrote are kept.`}
        size="sm"
      >
        <div className="flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={() => setConfirmDelete(null)}
            disabled={deleting}
            className="rounded-base border border-grey-30 px-4 py-2 text-sm font-medium text-grey-90 transition-colors hover:bg-grey-10 disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={remove}
            disabled={deleting}
            className="rounded-base bg-rose-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-rose-700 disabled:opacity-50"
          >
            {deleting ? "Deleting..." : "Delete agent"}
          </button>
        </div>
      </Modal>

      {wizard && token && (
        <AgentWizard
          token={token}
          agentId={wizard.id}
          initialStep={wizard.step}
          onClose={() => {
            setWizard(null)
            load()
          }}
          onSaved={upsert}
        />
      )}
    </div>
  )
}
