/** Countries merchants can target ads at — ISO-3166 alpha-2 + display name.
 *  Used by the advertising wizard's location picker (never raw code entry). */
export const AD_COUNTRIES: { code: string; name: string }[] = [
  { code: "US", name: "United States" }, { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" }, { code: "AU", name: "Australia" },
  { code: "BD", name: "Bangladesh" }, { code: "IN", name: "India" },
  { code: "PK", name: "Pakistan" }, { code: "LK", name: "Sri Lanka" }, { code: "NP", name: "Nepal" },
  { code: "DE", name: "Germany" }, { code: "FR", name: "France" }, { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" }, { code: "PT", name: "Portugal" }, { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" }, { code: "CH", name: "Switzerland" }, { code: "AT", name: "Austria" },
  { code: "IE", name: "Ireland" }, { code: "SE", name: "Sweden" }, { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" }, { code: "FI", name: "Finland" }, { code: "IS", name: "Iceland" },
  { code: "PL", name: "Poland" }, { code: "CZ", name: "Czechia" }, { code: "SK", name: "Slovakia" },
  { code: "HU", name: "Hungary" }, { code: "RO", name: "Romania" }, { code: "BG", name: "Bulgaria" },
  { code: "GR", name: "Greece" }, { code: "HR", name: "Croatia" }, { code: "SI", name: "Slovenia" },
  { code: "RS", name: "Serbia" }, { code: "UA", name: "Ukraine" }, { code: "TR", name: "Turkey" },
  { code: "EE", name: "Estonia" }, { code: "LV", name: "Latvia" }, { code: "LT", name: "Lithuania" },
  { code: "AE", name: "United Arab Emirates" }, { code: "SA", name: "Saudi Arabia" },
  { code: "QA", name: "Qatar" }, { code: "KW", name: "Kuwait" }, { code: "BH", name: "Bahrain" },
  { code: "OM", name: "Oman" }, { code: "JO", name: "Jordan" }, { code: "LB", name: "Lebanon" },
  { code: "IL", name: "Israel" }, { code: "EG", name: "Egypt" }, { code: "MA", name: "Morocco" },
  { code: "TN", name: "Tunisia" }, { code: "DZ", name: "Algeria" },
  { code: "NG", name: "Nigeria" }, { code: "GH", name: "Ghana" }, { code: "KE", name: "Kenya" },
  { code: "TZ", name: "Tanzania" }, { code: "UG", name: "Uganda" }, { code: "ET", name: "Ethiopia" },
  { code: "ZA", name: "South Africa" }, { code: "SN", name: "Senegal" }, { code: "CI", name: "Ivory Coast" },
  { code: "JP", name: "Japan" }, { code: "KR", name: "South Korea" }, { code: "CN", name: "China" },
  { code: "HK", name: "Hong Kong" }, { code: "TW", name: "Taiwan" }, { code: "SG", name: "Singapore" },
  { code: "MY", name: "Malaysia" }, { code: "TH", name: "Thailand" }, { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Philippines" }, { code: "ID", name: "Indonesia" }, { code: "MM", name: "Myanmar" },
  { code: "KH", name: "Cambodia" }, { code: "MN", name: "Mongolia" }, { code: "KZ", name: "Kazakhstan" },
  { code: "UZ", name: "Uzbekistan" }, { code: "AZ", name: "Azerbaijan" }, { code: "GE", name: "Georgia" },
  { code: "AM", name: "Armenia" },
  { code: "MX", name: "Mexico" }, { code: "BR", name: "Brazil" }, { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" }, { code: "CO", name: "Colombia" }, { code: "PE", name: "Peru" },
  { code: "EC", name: "Ecuador" }, { code: "UY", name: "Uruguay" }, { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivia" }, { code: "VE", name: "Venezuela" }, { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" }, { code: "GT", name: "Guatemala" }, { code: "DO", name: "Dominican Republic" },
  { code: "JM", name: "Jamaica" }, { code: "TT", name: "Trinidad and Tobago" },
  { code: "NZ", name: "New Zealand" }, { code: "FJ", name: "Fiji" }, { code: "PG", name: "Papua New Guinea" },
  { code: "MV", name: "Maldives" }, { code: "BT", name: "Bhutan" }, { code: "BN", name: "Brunei" },
  { code: "CY", name: "Cyprus" }, { code: "MT", name: "Malta" }, { code: "LU", name: "Luxembourg" },
  { code: "AL", name: "Albania" }, { code: "MK", name: "North Macedonia" }, { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "MD", name: "Moldova" }, { code: "ME", name: "Montenegro" },
  { code: "IQ", name: "Iraq" }, { code: "AF", name: "Afghanistan" },
  { code: "ZM", name: "Zambia" }, { code: "ZW", name: "Zimbabwe" }, { code: "BW", name: "Botswana" },
  { code: "NA", name: "Namibia" }, { code: "MZ", name: "Mozambique" }, { code: "AO", name: "Angola" },
  { code: "CM", name: "Cameroon" }, { code: "CD", name: "DR Congo" }, { code: "RW", name: "Rwanda" },
  { code: "MU", name: "Mauritius" }, { code: "MG", name: "Madagascar" },
]

export const countryName = (code: string): string =>
  AD_COUNTRIES.find((c) => c.code === code)?.name ?? code
